### ISSUE TITLE
Metadata -> Combine Name and Submitted By

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/stories#4]

**Comment by biru-codeastromer** [comment]
Hi Sir @krisstern,
I hope you're doing well! While the issue in PR #79 is still under review, I came across this Issue. I believe I can make a valuable contribution to this issue as well.
Could you please let me know if it’s okay for me to start working on it in the meantime?

**Comment by krisstern** [comment]
Hi @biru-codeastromer you are welcome to submit a patch for this issue if you believe you understand what the requirements are.

**Comment by biru-codeastromer** [comment]
@krisstern Thanks Sir, I will see the requirements more and work on this.

**Comment by biru-codeastromer** [comment]
> Hi @biru-codeastromer you are welcome to submit a patch for this issue if you believe you understand what the requirements are.

Hi Sir,

I hope you're doing well! I wanted to provide a bit more context on the approach I took for solving this issue by combining the `name` and `submitted_by` fields into `authored_by`.

In my PR #80, I created a separate script called `combineFields.js` to handle the transformation of these fields. This script processes the YAML files, consolidates the fields into `authored_by`, and updates the files accordingly.

However, I was wondering if it would be better to handle this transformation directly within the `gatsby-node.js` file during the build process. Here are the two approaches:

## Approach 1: Separate `combineFields.js` Script
- A standalone script processes the YAML files and updates the fields before the build.
- Keeps the logic separate from Gatsby's build process.

## Approach 2: Handle in `gatsby-node.js`
- Integrate the field transformation directly within the `onCreateNode` function in `gatsby-node.js`.
- Processes the fields during Gatsby's build process without the need for a separate script.

I would appreciate your input on which approach you think is more suitable for this project. Thank you!

**Comment by halkeye** [comment]
Boo past me for not writing up more notes

A one time fixing of data is probably the best solution 

So you have an example of one with name and submitted by?

**Comment by biru-codeastromer** [comment]
> Boo past me for not writing up more notes
> 
> A one time fixing of data is probably the best solution
> 
> So you have an example of one with name and submitted by?


Hi @halkeye Sir,  

Thank you for clarifying the approach! Based on your's and Krisstern Sir's guidance, I opted for a one-time data transformation to combine the `name` and `submitted_by` fields into `authored_by`.  

Here’s an example of the transformation:  

## Before:
```yaml
name: Amandep Singh  
submitted_by: Amandep Singh  
```

## After:
```yaml
authored_by: Amandep Singh  
```

For a more detailed example, the updated YAML files look like this:  

```yaml
map:
  location: India
  industries:
    - Telecomunications
  latitude: "30.7311236"
  longitude: "76.825458"
metadata:
  title: This India-based IT services organization stepped up to help a leading
    telecom company expand their Jenkins pipeline.
  organization: Information technology services and business process outsourcing company
  industries:
    - Telecommunication
  programming_languages:
    - Java
  platforms:
    - ": Linux"
    - Docker or Kubernetes
  version_control_systems:
    - Bitbucket Server
  build_tools:
    - Maven
  community_supports:
    - Jenkins.io websites & blogs
    - spoke with colleagues and peers
  authored_by: Amandep Singh
body_content:
  title: Building, testing, and deploying a Jenkins pipeline for a leading
    telecommunications company.
  paragraphs:
    - "**Background:** When a large telecom company needed help enhancing their
      Jenkins pipeline, they turned to one of India's leading IT services
      companies for support..."
title: Jenkins is the way to create an awesome pipeline
date: 2020-07-14T13:54:24.000Z
post_name: jenkins-is-the-way-to-create-an-awesome-pipeline
quotes:
  - from: Amandep Singh, Senior Engineer
    content: Since Jenkins is open source, the implementation was easy whereas,
      other tools tend to be quite difficult to use.
    image: ./quote.png
image: noun_Telephone_2627962-300x300.png
tag_line: Enabling microservices for a large telecom
```

Hoping this aligns now with the issue solving requirements.

Thanks again for your guidance!
